[[main]]
  name = "Posts"
  pageRef = "post"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Software"
  pageRef = "software"
  weight = 40

[[main]]
  name = "Join the Lab"
  pageRef = "join_the_lab"
  weight = 50
